#!/bin/bash

# Führe Rasa aus
source /home/suturo/suturo23_24/nlp_ws/venv/bin/activate
cd /home/suturo/suturo23_24/nlp_ws/src/Rasa/rasa
rasa run --enable-api

# cd /home/suturo/suturo23_24/nlp_ws/src/suturo_nlp/activate_language_processing/scripts
# python3 nlp_receptionist.py
# Aktiviere das Virtual Environment







# terminator -e "/bin/bash -c 'source ~/.bashrc && cd cd /home/suturo/suturo23_24/nlp_ws/src/Rasa/rasa; rasa run --enable-api; sleep 10 '"
# Befehl zum Öffnen eines neuen Terminator-Fensters und Ausführen der Befehle
